### ISSUE TITLE
TFT_GD32 code not compiling

### ISSUE THREAD

**Issue by MiLeG** [Seeed-Studio/Seeed_Arduino_LCD#5]
Greetings,

I have tried to compile your code on the TFT_GD32 branch of the repository and an error surrounding the SPI library occurs in multiple files:
`lib\Seeed_Arduino_LCD\TFT_eSPI.h:107:12: fatal error: SPI.h: No such file or directory
lib\Seeed_Arduino_LCD/TFT_Interface.h:71:12: fatal error: SPI.h: No such file or directory
src\main.cpp:13:10: fatal error: SPI.h: No such file or directory`

I am compiling the code with the latest version of the gd32 core and I was hoping you could give me some clue as to how this problem could be solved?

I tried replacing all the lines
`#include <SPI.h>`
with this
`#include <gd32vf103_spi.h>`
because it was the only SPI-related header file in the core, but that in turn causes more errors than it fixes.

**Comment by LynnL4** [comment]
Hi:
   you could try to remove this include,

**Comment by Pillar1989** [comment]
@MiLeG Have you worked it out?

**Comment by MiLeG** [comment]
Not exactly, but my code is compiling with the stm32duino core instead of the gd32 core and itseems to run well on my hardware.
This issue is probably caused by me using a different gd32 core version than what was used to compile this project.
I'll consider this solved and this issue closed
